# Generated by Django 5.2.12 on 2026-04-28 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nama Loket')),
                ('number', models.IntegerField(unique=True, verbose_name='Nomor Loket')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Loket',
                'verbose_name_plural': 'Loket',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Layanan')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Kode Layanan')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Jenis Layanan',
                'verbose_name_plural': 'Jenis Layanan',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='ID Petugas')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='No. HP')),
                ('counter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='antrian.counter', verbose_name='Loket')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Petugas',
                'verbose_name_plural': 'Petugas',
            },
        ),
        migrations.CreateModel(
            name='QueueTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=10, verbose_name='Nomor Antrian')),
                ('tracking_code', models.CharField(max_length=10, unique=True, verbose_name='Kode Tracking')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Nama Pelanggan')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Nomor HP')),
                ('status', models.CharField(choices=[('waiting', 'Menunggu'), ('called', 'Dipanggil'), ('serving', 'Sedang Dilayani'), ('done', 'Selesai'), ('skipped', 'Dilewati'), ('cancelled', 'Dibatalkan')], default='waiting', max_length=15, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Daftar')),
                ('called_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Dipanggil')),
                ('served_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Dilayani')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Selesai')),
                ('counter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='antrian.counter', verbose_name='Loket')),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='antrian.officer', verbose_name='Petugas')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antrian.servicetype', verbose_name='Jenis Layanan')),
            ],
            options={
                'verbose_name': 'Tiket Antrian',
                'verbose_name_plural': 'Tiket Antrian',
                'ordering': ['created_at'],
            },
        ),
    ]
